#122 #9 Adding Premake support to OpenEAGGR
riskaware-ltd/open-eaggr pull request #10
Opened 2023-08-10 09:03 UTC by OlekRaymond

Added some helpful messages to a chosen system test to aid in debugging. Changed TestMacros.hpp to avoid underscores in google test.

2023-08-15 12:45 UTC, EmilySTyler requested changes
Minor comments, also:

In EAGGR/premake:
- I think `removefiles { "**/3rdParty/**" }` should be `removefiles { "./3rdParty/**" }`
- The vpaths should have OpenEAGGR in front

2023-08-15 12:45 UTC, EmilySTyler commented on EAGGRTestHarness/SystemTests/ImportExport/KmlExporterISEA4TSystemTest.cpp
> +  const std::string outputFilePath("OpenEAGGR/EAGGRTestHarness/TestData/ISEA4TIcosahedronAllFacesKmlExport.kml");
Ctrl-F for "ouput", should be "output"

2023-08-15 12:45 UTC, EmilySTyler commented on EAGGRTestHarness/TestMacros.hpp
> -   TEST(EvaluationTest##_##TestBase, TestName)
Why did you change these? Just wondering

2023-08-16 10:04 UTC, OlekRaymond commented on EAGGRTestHarness/TestMacros.hpp
> -   TEST(EvaluationTest##_##TestBase, TestName)
No underscored in google test names

2023-08-16 10:24 UTC, OlekRaymond commented
> In EAGGR/premake:
> * I think `removefiles { "**/3rdParty/**" }` should be `removefiles { "./3rdParty/**" }`
Done
> * The vpaths should have OpenEAGGR in front
Nope? They are in the OpenEAGGR project, no need for OpenEAGGR/OpenEAGGR/HeaderFiles ?

2023-08-16 10:24 UTC, OlekRaymond commented on EAGGRTestHarness/SystemTests/ImportExport/KmlExporterISEA4TSystemTest.cpp
> +  const std::string outputFilePath("OpenEAGGR/EAGGRTestHarness/TestData/ISEA4TIcosahedronAllFacesKmlExport.kml");
Done

2023-08-16 10:41 UTC, EmilySTyler approved these changes

2023-08-16 10:41 UTC, merged