refs #6 Upates to use gdal 3.5.2 and proj 9.0.1 and some other gcc up…
riskaware-ltd/open-eaggr pull request #7
Opened 2023-02-21 10:11 UTC by sachadarwin

…dates.

2023-02-21 15:06 UTC, OlekRaymond requested changes
We may only want to pull the bits from openEAGGR we need to reduce the amount of code that needs to be pulled for people to build snaptrap (like the python 2 wrapper) Also as openEAGGR is open source is a fork more appropriate than a branch?

2023-02-21 15:06 UTC, OlekRaymond commented on EAGGR/API/eaggr_api.h
>  #endif
do we not need to keep blank EXPORT define in Linux?

2023-02-21 15:06 UTC, OlekRaymond commented on EAGGR/Src/CoordinateConversion/CoordinateConverter.cpp
> +      c.lpzt.t       = HUGE_VAL;
strange alignment of variables here

2023-02-21 15:06 UTC, OlekRaymond commented on EAGGR/Src/CoordinateConversion/CoordinateConverter.cpp
> +      PJ_COORD c;
consider using a more informative name

2023-02-21 15:06 UTC, OlekRaymond commented on EAGGR/Src/CoordinateConversion/CoordinateConverter.cpp
> +        const char* error = proj_errno_string(returnCode);
Consider a more informative name ( ` errorMessage `?)

2023-02-21 15:06 UTC, OlekRaymond commented on EAGGR/Src/CoordinateConversion/CoordinateConverter.cpp
>          throw EAGGRException(stream.str());
If this is just reused boiler plate code should it be in it's own function, if so the string stream can be removed in favour for an append.

2023-02-21 15:06 UTC, OlekRaymond commented on EAGGR/Src/Model/IGrid/IHierarchicalGrid/Aperture4TriangleGrid.hpp
> +            static constexpr double m_HEIGHT_TO_EDGE_RATIO = 1.732050807568877293527446341505872366 / 2.0;
don't know if these need to be ` constexpr ` , if not change to ` const ` and re-add the sqrt(3.0) otherwise write a comment to explain this is root 3.

2023-02-23 13:28 UTC, OlekRaymond requested changes
Small things again

2023-02-23 13:28 UTC, OlekRaymond commented on EAGGR/Src/CoordinateConversion/CoordinateConverter.cpp
> +        if (m_ctx_p == NULL)
This could have a more informative name

2023-02-23 13:28 UTC, OlekRaymond commented on EAGGR/Src/CoordinateConversion/CoordinateConverter.cpp
> +      PJ_COORD c;
c should have a more informative name

2023-02-23 13:28 UTC, OlekRaymond commented on EAGGR/Src/CoordinateConversion/CoordinateConverter.cpp
> +      PJ_COORD c;
c could have a more informative name

2023-02-23 13:28 UTC, OlekRaymond commented on EAGGR/Src/ImportExport/KmlExporter.cpp
> +        }
Left from debugging?

2023-02-23 21:30 UTC, sachadarwin commented on EAGGR/API/eaggr_api.h
>  #endif
done.

2023-02-23 21:31 UTC, sachadarwin commented on EAGGR/Src/CoordinateConversion/CoordinateConverter.cpp
> +        if (m_ctx_p == NULL)
done.

2023-02-23 21:32 UTC, sachadarwin commented on EAGGR/Src/CoordinateConversion/CoordinateConverter.cpp
> +      PJ_COORD c;
done

2023-02-23 21:36 UTC, sachadarwin commented on EAGGR/Src/CoordinateConversion/CoordinateConverter.cpp
>          throw EAGGRException(stream.str());
Added common function.

2023-02-23 21:36 UTC, sachadarwin commented on EAGGR/Src/CoordinateConversion/CoordinateConverter.cpp
> +      PJ_COORD c;
done

2023-02-23 21:37 UTC, sachadarwin commented on EAGGR/Src/ImportExport/KmlExporter.cpp
> +        }
removed

2023-02-23 21:41 UTC, sachadarwin commented on EAGGR/Src/Model/IGrid/IHierarchicalGrid/Aperture4TriangleGrid.hpp
> +            static constexpr double m_HEIGHT_TO_EDGE_RATIO = 1.732050807568877293527446341505872366 / 2.0;
kept as constexpr but added back sqrt

2023-02-24 10:37 UTC, OlekRaymond commented on EAGGR/Src/CoordinateConversion/CoordinateConverter.cpp
> +            throw EAGGR::EAGGRException(stream.str());
Think a string append is faster and cleaner (you do need to create a std::string from C string)

2023-02-24 10:37 UTC, OlekRaymond commented on EAGGR/Src/Model/IGrid/IHierarchicalGrid/Aperture4TriangleGrid.hpp
> +            static constexpr double m_HEIGHT_TO_EDGE_RATIO = 1.732050807568877293527446341505872366 / 2.0;
We had troubles with sqrt in windows as it doesn't seem to have a constexpr sqrt (we may have been using c++14 version and now we aren't so maybe that fixed it. running on windows now

2023-02-24 10:40 UTC, OlekRaymond requested changes
Breaks on windows :'(

2023-02-24 12:22 UTC, sachadarwin commented on EAGGR/Src/CoordinateConversion/CoordinateConverter.cpp
> +            throw EAGGR::EAGGRException(stream.str());
Done

2023-02-24 12:51 UTC, OlekRaymond approved these changes
Looks good :D

2023-02-24 13:04 UTC, merged